### PR TITLE
Update Preferences.sublime-settings

### PR DESCRIPTION
**Pull request by itsjzt**
😆 🚀 🏷 merge it

### CODE REVIEW

**Comment by sanatankc** [comment]
Oh @itsjzt! your pull doesn't meet with our standards. kindly review our guidlines.

**Comment by itsjzt** [comment]
Lol 🥇

**Comment by sanatankc** [comment]
but it can meet our guidlines if you will accept my pull. Deal? 😂

**Comment by itsjzt** [comment]
👍

**Pull request merged**
